<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NetArchTest.eNhancedEdition" />
    <PackageReference Include="xunit.v3.mtp-v2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Angur.Domain\Angur.Domain.csproj" />
    <ProjectReference Include="..\..\src\Angur.Application\Angur.Application.csproj" />
    <ProjectReference Include="..\..\src\Angur.Infrastructure\Angur.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Angur.Api\Angur.Api.csproj" />
  </ItemGroup>

</Project>
